name: cuML wheels

on:
  push:
    branches:
      - 'pull-request/[0-9]+'

jobs:
  libcuml-wheel-amd64:
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-amd64.yml@feat/wheel-ci-actions
    with:
      package-name: libcuml_cuda11
      package-dir: cpp
      python-version: "3.8"
      cibw-environment: "PYTHON_PACKAGE_CUDA_SUFFIX='-cuda11'"
      cibw-before-build: "pip install rmm-cuda11 raft-cuda11 libraft-cuda11 --index-url https://pypi.k8s.rapids.ai/simple"
      skbuild-configure-options: '-DCMAKE_MESSAGE_LOG_LEVEL=DEBUG -DBUILD_CUML_C_LIBRARY=OFF -DBUILD_CUML_CPP_LIBRARY=ON -DBUILD_CUML_EXAMPLES=OFF -DBUILD_CUML_TESTS=OFF -DBUILD_PRIMS_TESTS=OFF -DBUILD_CUML_BENCH=OFF -DBUILD_CUML_PRIMS_BENCH=OFF'
      gpu-smoketest: ""
      auditwheel-repair-override: "cp {wheel} {dest_dir}"
    secrets: inherit
  cuml-wheel-amd64-38:
    needs: libcuml-wheel-amd64
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-amd64.yml@feat/wheel-ci-actions
    with:
      package-name: cuml
      package-dir: python
      python-version: "3.8"
      cibw-environment: "PYTHON_PACKAGE_CUDA_SUFFIX='-cuda11'"
      cibw-before-all: ""
      cibw-before-build: ""
      skbuild-configure-options: "-DFIND_CUML_CPP=ON"
      gpu-smoketest-before: "pip install rmm-cuda11 cudf-cuda11 --index-url https://pypi.k8s.rapids.ai/simple"
      gpu-smoketest: "import cudf; from cuml.cluster import DBSCAN; gdf_float = cudf.DataFrame(); gdf_float['0'] = [1.0, 2.0, 5.0]; gdf_float['1'] = [4.0, 2.0, 1.0]; gdf_float['2'] = [4.0, 2.0, 1.0]; dbscan_float = DBSCAN(eps=1.0, min_samples=1); dbscan_float.fit(gdf_float); print(dbscan_float.labels_)"
    secrets: inherit
  cuml-wheel-amd64-39:
    needs: libcuml-wheel-amd64
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-amd64.yml@feat/wheel-ci-actions
    with:
      package-name: cuml
      package-dir: python
      python-version: "3.9"
      cibw-environment: "PYTHON_PACKAGE_CUDA_SUFFIX='-cuda11'"
      cibw-before-all: ""
      cibw-before-build: ""
      skbuild-configure-options: "-DFIND_CUML_CPP=ON"
      gpu-smoketest-before: "pip install rmm-cuda11 cudf-cuda11 --index-url https://pypi.k8s.rapids.ai/simple"
      gpu-smoketest: "import cudf; from cuml.cluster import DBSCAN; gdf_float = cudf.DataFrame(); gdf_float['0'] = [1.0, 2.0, 5.0]; gdf_float['1'] = [4.0, 2.0, 1.0]; gdf_float['2'] = [4.0, 2.0, 1.0]; dbscan_float = DBSCAN(eps=1.0, min_samples=1); dbscan_float.fit(gdf_float); print(dbscan_float.labels_)"
    secrets: inherit
  libcuml-wheel-arm64:
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-arm64.yml@feat/wheel-ci-actions
    with:
      package-name: libcuml_cuda11
      package-dir: cpp
      python-version: "3.8"
      cibw-environment: "PYTHON_PACKAGE_CUDA_SUFFIX='-cuda11'"
      cibw-before-build: "pip install rmm-cuda11 raft-cuda11 libraft-cuda11 --index-url https://pypi.k8s.rapids.ai/simple"
      skbuild-configure-options: '-DCMAKE_MESSAGE_LOG_LEVEL=DEBUG -DBUILD_CUML_C_LIBRARY=OFF -DBUILD_CUML_CPP_LIBRARY=ON -DBUILD_CUML_EXAMPLES=OFF -DBUILD_CUML_TESTS=OFF -DBUILD_PRIMS_TESTS=OFF -DBUILD_CUML_BENCH=OFF -DBUILD_CUML_PRIMS_BENCH=OFF'
      gpu-smoketest: ""
      auditwheel-repair-override: "cp {wheel} {dest_dir}"
    secrets: inherit
  cuml-wheel-arm64-38:
    needs: libcuml-wheel-arm64
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-arm64.yml@feat/wheel-ci-actions
    with:
      package-name: cuml
      package-dir: python
      python-version: "3.8"
      cibw-environment: "PYTHON_PACKAGE_CUDA_SUFFIX='-cuda11'"
      cibw-before-all: ""
      cibw-before-build: ""
      skbuild-configure-options: "-DFIND_CUML_CPP=ON"
      gpu-smoketest-before: "pip install rmm-cuda11 cudf-cuda11 --index-url https://pypi.k8s.rapids.ai/simple"
      gpu-smoketest: "import cudf; from cuml.cluster import DBSCAN; gdf_float = cudf.DataFrame(); gdf_float['0'] = [1.0, 2.0, 5.0]; gdf_float['1'] = [4.0, 2.0, 1.0]; gdf_float['2'] = [4.0, 2.0, 1.0]; dbscan_float = DBSCAN(eps=1.0, min_samples=1); dbscan_float.fit(gdf_float); print(dbscan_float.labels_)"
    secrets: inherit
  cuml-wheel-arm64-39:
    needs: libcuml-wheel-arm64
    uses: rapidsai/shared-action-workflows/.github/workflows/wheels-arm64.yml@feat/wheel-ci-actions
    with:
      package-name: cuml
      package-dir: python
      python-version: "3.9"
      cibw-environment: "PYTHON_PACKAGE_CUDA_SUFFIX='-cuda11'"
      cibw-before-all: ""
      cibw-before-build: ""
      skbuild-configure-options: "-DFIND_CUML_CPP=ON"
      gpu-smoketest-before: "pip install rmm-cuda11 cudf-cuda11 --index-url https://pypi.k8s.rapids.ai/simple"
      gpu-smoketest: "import cudf; from cuml.cluster import DBSCAN; gdf_float = cudf.DataFrame(); gdf_float['0'] = [1.0, 2.0, 5.0]; gdf_float['1'] = [4.0, 2.0, 1.0]; gdf_float['2'] = [4.0, 2.0, 1.0]; dbscan_float = DBSCAN(eps=1.0, min_samples=1); dbscan_float.fit(gdf_float); print(dbscan_float.labels_)"
    secrets: inherit
